version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.15
    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python -m virtualenv env
            . env/bin/activate
            pip install -r requirements.txt
      - run:
          name: flake8
          command: |
            . env/bin/activate
            flake8 main.py
            flake8 test_siklik.py
            flake8 siklik.py
      - save_cache:
          paths:
            - ./env
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run tests
          command: |
            . env/bin/activate
            pytest

      - store_artifacts:
          path: test-reports
          destination: test-reports